name: Node.js CI

on:
  push:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Suhail-Md repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install libraries
      run: npm install

    - name: Start Suhail-Md
        run:|
          echo "Running Queen Anju bot in auto-restart mode..."
          timeout 18000 bash -c 'while true; do node queen.js || echo "Bot crashed, restarting..."; sleep 2; done'

    - name: Re-Trigger Workflow
      if: always()
        run:|
          echo "Re-running workflow..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/loop-runner.yml/dispatches \
            -d '{"ref":"main"}'
      env:
          OWNER_NAME: Mr. Kalulu 
          OWNER_NUMBER: 255626753818
          SESSION_ID:

      run: npm start
